const Map<String, String> en = {
  "Hello": "Hello",
  "Welcome": "Welcome",
  "Seller_App": "Seller App",
  "Version": "Version",
  "Home": "Home",
  "Password": "Password",
  "Input_ID": "Input ID",
  "Input_Password": "Input Password",
  "Login": "Login",
  "Login_Success": "Login Success",
  "Menu": "Menu",
  "ID": "ID",
  "Draw": "Draw",
  "Draw-Date": "Draw Date",
  "No": "No",
  "Digit": "Digit",
  "Amount": "Amount",
  "Del": "Del",
  "Sale_Header": "Sale Header",
  "Customer_Phone": "Customer Phone",
  "Total": "Total",
  "23456D": "23456D",
  "4_Animals": "4 Animals",
  "2D": "2D",
  "3D": "3D",
  "4D": "4D",
  "5D": "5D",
  "6D": "6D",
  "Sale": "Sale",
  "Random": "Random",
  "Shuffle": "Shuffle",
  "Full_Set": "Full Set",
  "Print": "Print",
  "Print_Test": "Print Test",
  "Register_Information": "Register Information",
  "Promotion_Announcement": "Promotion Announcement",
  "Lottery_Result": "Lottery Result",
  "Change_Password": "Change Password",
  "Change_Language": "Change Language",
  "Logout": "Logout",
  "Remaining_Wallet": "Remaining Wallet",
  "Seller_ID": "Seller ID",
  "Name_Of_Seller": "Name Of Seller",
  "Phone_Number": "Phone Number",
  "Bank_Name": "Bank Name",
  "Account_Number": "Account Number",
  "Account_Name": "Account Name",
  "Update": "Update",
  "Database_Exception": "Database Exception",
  "Date": "Date",
  "Bill": "Bill",
  "Customer_Phone_Number": "Customer Phone Number",
  "Animal": "Animal",
  "Check_Winner": "Check Winner",
  "Search": "Search",
  "Wining_Digit": "Wining Digit",
  "2Digit_6Digit": "2Digit 6Digit",
  "440_Animals": "440 Animals",
  "Please_Change_Password": "Please Change Password",
  "Old_Password": "Old Password",
  "New_Password": "New Password",
  "Confirm_Password": "Confirm Password",
  "Cancel": "Cancel",
  "Okay": "Okay",
  "InputMoney": "Input Money",
  "Back": "Back",
};
