// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QQdmRsech8ARvgyNCUrkF0LjsTcd12o',
    appId: '1:893728763626:web:cbe8e788f134c2863e7193',
    messagingSenderId: '893728763626',
    projectId: 'lodlaos',
    authDomain: 'lodlaos.firebaseapp.com',
    storageBucket: 'lodlaos.appspot.com',
    measurementId: 'G-NDBDS8SFB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBww2to6Znqv7BTJL4ZFlaX3bbwDS6WR_M',
    appId: '1:893728763626:android:59bffa35db4e57fe3e7193',
    messagingSenderId: '893728763626',
    projectId: 'lodlaos',
    storageBucket: 'lodlaos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ln1PtgjpHEMHVQRxGCR864Ls1NRJzOQ',
    appId: '1:893728763626:ios:9739f20acef3c9213e7193',
    messagingSenderId: '893728763626',
    projectId: 'lodlaos',
    storageBucket: 'lodlaos.appspot.com',
    iosClientId: '893728763626-0hpipnmob9og9jrtcl0jilmnacre2ihf.apps.googleusercontent.com',
    iosBundleId: 'com.technology.netviet.lodLaos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ln1PtgjpHEMHVQRxGCR864Ls1NRJzOQ',
    appId: '1:893728763626:ios:9739f20acef3c9213e7193',
    messagingSenderId: '893728763626',
    projectId: 'lodlaos',
    storageBucket: 'lodlaos.appspot.com',
    iosClientId: '893728763626-0hpipnmob9og9jrtcl0jilmnacre2ihf.apps.googleusercontent.com',
    iosBundleId: 'com.technology.netviet.lodLaos',
  );
}
